apiVersion: v1
kind: Service
metadata:
  name: hello-world-workflow
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: hello-world-workflow
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000